jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: ${JENKINS_ADMIN_ID}
        password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "USER:Overall/Administer:admin"
      - "GROUP:Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
tool:
  maven:
    installations:
    - name: maven
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.8.7"
credentials:
  system:
    domainCredentials:
    - credentials:
      - gitLabApiTokenImpl:
          scope: SYSTEM
          id: gitlab_token
          apiToken: "${GITLAB_TOKEN}"
          description: "Gitlab Token"
      - usernamePassword:
          scope: GLOBAL
          id: "gitlab_login"
          username: "andrew"
          password: "${GITLAB_TOKEN}"
unclassified:
  gitlabconnectionconfig:
    connections:
    - apiTokenId: gitlab_token
      clientBuilderId: "autodetect"
      connectionTimeout: 20
      ignoreCertificateErrors: true
      name: "devops"
      readTimeout: 10
      url: "https://gitlab.com/"
  location:
    url: http://${JENKINS_HOST_IP}:8080/
jobs:
- script: >
    pipelineJob('devops') {
      triggers {
        gitlabPush {
          buildOnMergeRequestEvents(true)
          buildOnPushEvents(true)
          enableCiSkip(false)
          setBuildDescription(false)
          rebuildOpenMergeRequest('never')
        }
      }
      definition {
        cpsScm {
          scm {
            git {
              remote {
                url("https://gitlab.com/kp931/devops_test.git")
                credentials("gitlab_login")
              }
              branch('*/main')
            }
          }
        }
      }
    }
